/**
* @author Francesco Baldi
* @mail francesco.baldi1987@gmail.com
* @class bld.generator.report.excel.SheetDynamicData.java
*/
package bld.generator.report.excel;

import java.util.HashMap;
import java.util.Map;

import javax.validation.constraints.Size;

import org.apache.commons.lang3.StringUtils;

import bld.common.spreadsheet.utils.SpreadsheetUtils;
import bld.generator.report.excel.data.ExtraColumnAnnotation;

/**
 * The Class SheetDynamicData.
 * 
 * @param <T> the generic type <br>
 *            SheetDynamicData extends
 *            {@link bld.generator.report.excel.SheetData}, it manages dynamic
 *            columns through the mapExtraColumnAnnotation field. <br>
 *            mapExtraColumnAnnotation and mapValue(is a field of
 *            {@link bld.generator.report.excel.DynamicRowSheet}) have the same
 *            keys. <br>
 *            Below an example of table generated by merging
 *            {@link bld.generator.report.excel.SheetDynamicData} and
 *            {@link bld.generator.report.excel.DynamicRowSheet} classes.
 *            <table style="width:100%;">
 *            <tr>
 *            <th style="width: 4%"></th>
 *            <th style="width: 16%; border: 1px solid #666; text-align:
 *            center;">column name by field 1</th>
 *            <th style="width: 16%; border: 1px solid #666; text-align:
 *            center;">column name by field 2</th>
 *            <th style="width: 16%; border: 1px solid #666; text-align:
 *            center;">column name by mapExtraColumnAnnotation 1</th>
 *            <th style="width: 16%; border: 1px solid #666; text-align:
 *            center;">column name by mapExtraColumnAnnotation ...N</th>
 *            <th style="width: 16%; border: 1px solid #666; text-align:
 *            center;">column name by field 3</th>
 *            <th style="width: 16%; border: 1px solid #666; text-align:
 *            center;">column name by field ...N</th>
 *            </tr>
 *            <tr>
 *            <td style="width: 8%; ">row 1</td>
 *            <td style="width: 16%; border: 1px solid #666;">value by field
 *            1</td>
 *            <td style="width: 16%; border: 1px solid #666">value by field
 *            2</td>
 *            <td style="width: 16%; border: 1px solid #666">value by mapValue
 *            1</td>
 *            <td style="width: 16%; border: 1px solid #666">value by mapValue
 *            ...N</td>
 *            <td style="width: 16%; border: 1px solid #666">value by field
 *            3</td>
 *            <td style="width: 16%; border: 1px solid #666">value by field
 *            ...N</td>
 *            </tr>
 *            <tr>
 *            <td style="width: 8%; ">row 2</td>
 *            <td style="width: 16%; border: 1px solid #666;">value by field
 *            1</td>
 *            <td style="width: 16%; border: 1px solid #666">value by field
 *            2</td>
 *            <td style="width: 16%; border: 1px solid #666">value by mapValue
 *            1</td>
 *            <td style="width: 16%; border: 1px solid #666">value by mapValue
 *            ...N</td>
 *            <td style="width: 16%; border: 1px solid #666">value by field
 *            3</td>
 *            <td style="width: 16%; border: 1px solid #666">value by field
 *            ...N</td>
 *            </tr>
 *            <tr>
 *            <td style="width: 8%; ">row N</td>
 *            <td style="width: 16%; border: 1px solid #666;">value by field
 *            1</td>
 *            <td style="width: 16%; border: 1px solid #666">value by field
 *            2</td>
 *            <td style="width: 16%; border: 1px solid #666">value by mapValue
 *            1</td>
 *            <td style="width: 16%; border: 1px solid #666">value by mapValue
 *            ...N</td>
 *            <td style="width: 16%; border: 1px solid #666">value by field
 *            3</td>
 *            <td style="width: 16%; border: 1px solid #666">value by field
 *            ...N</td>
 *            </tr>
 * 
 *            </table>
 */
public abstract class SheetDynamicData<T extends DynamicRowSheet> extends SheetData<T> implements DynamicColumn {

	/** The map extra column annotation. */
	private Map<String, ExtraColumnAnnotation> mapExtraColumnAnnotation;

	/**
	 * Instantiates a new sheet dynamic data.
	 *
	 * @param sheetName the name sheet
	 */
	public SheetDynamicData(@Size(max = SpreadsheetUtils.SHEET_NAME_SIZE) String sheetName) {
		super(sheetName);
		this.mapExtraColumnAnnotation = new HashMap<>();
	}

	/**
	 * Gets the map extra column annotation.
	 *
	 * @return the map extra column annotation
	 */
	public Map<String, ExtraColumnAnnotation> getMapExtraColumnAnnotation() {
		return mapExtraColumnAnnotation;
	}

	/**
	 * Sets the map extra column annotation.
	 *
	 * @param mapExtraColumnAnnotation the new map extra column annotation
	 */
	public void setMapExtraColumnAnnotation(Map<String, ExtraColumnAnnotation> mapExtraColumnAnnotation) {
		this.mapExtraColumnAnnotation = mapExtraColumnAnnotation;
	}

	public void addExtraColumn(String key, ExtraColumnAnnotation extraColumnAnnotation) {
		if (StringUtils.isNotBlank(key) && extraColumnAnnotation != null)
			this.mapExtraColumnAnnotation.put(key, extraColumnAnnotation);
	}

	/**
	 * Hash code.
	 *
	 * @return the int
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((mapExtraColumnAnnotation == null) ? 0 : mapExtraColumnAnnotation.hashCode());
		return result;
	}

	/**
	 * Equals.
	 *
	 * @param obj the obj
	 * @return true, if successful
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		SheetDynamicData<?> other = (SheetDynamicData<?>) obj;
		if (mapExtraColumnAnnotation == null) {
			if (other.mapExtraColumnAnnotation != null)
				return false;
		} else if (!mapExtraColumnAnnotation.equals(other.mapExtraColumnAnnotation))
			return false;
		return true;
	}

}
