/**
* @author Francesco Baldi
* @mail francesco.baldi1987@gmail.com
* @class com.bld.generator.report.excel.SheetSummary.java
*/

package com.bld.generator.report.excel;

import com.bld.common.spreadsheet.utils.SpreadsheetUtils;

import jakarta.validation.constraints.Size;

/**  
 * The Class SheetSummary.
 * <br>
 * SheetSummary is used for the generation of a summary sheet with 2 columns.<br>
 * They are:<br>
 * <ol>
 * <li>the name of the property.</li>
 * <li>The value.</li>
 * </ol>
 * To write the property name and value, you usually need to add the following 2 annotations for each field that represent this combination.
 * <ol>
 * <li>{@link com.bld.generator.report.excel.annotation.ExcelColumn}</li>
 * <li>{@link com.bld.generator.report.excel.annotation.ExcelCellLayout}</li>
 * </ol>
 * 
 * 
 * Below an example of table generated by SheetSummary classes.
 *<table style="width:50%; border: 1px solid #666">
 *  <tr>
 *    <th colspan="2" style="border: 1px solid #666; text-align: center;">Title</th>
 *  </tr>
 *  <tr>
 *    <td style="width:50%; border: 1px solid #666">property name of the field 1</td>
 *    <td style="width:50%; border: 1px solid #666">value of the field 1</td>
 *  </tr>
 *  <tr>
 *    <td style="width:50%; border: 1px solid #666">property name of the field 2</td>
 *    <td style="width:50%; border: 1px solid #666">value of the field 2</td>
 *  </tr>
 *  <tr>
 *    <td style="width:50%; border: 1px solid #666">property name of the field ...N</td>
 *    <td style="width:50%;border: 1px solid #666">value of the field ...N</td>
 *  </tr>
 *</table>
 */
public abstract class SheetSummary extends BaseSheet implements SheetComponent{

	/**
	 * Instantiates a new sheet summary.
	 *
	 * @param sheetName the name sheet
	 */
	public SheetSummary(@Size(max = SpreadsheetUtils.SHEET_NAME_SIZE) String sheetName) {
		super(sheetName);
	}

	
	
}
